services:
  postgres:
    image: postgres
    # shm_size: 128mb

    container_name: starter_db

    environment:
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
